--- Makefile	Sun Nov 18 17:52:42 2012 +0100
+++ Makefile	Sun Nov 25 00:43:08 2012 +0200
@@ -18,7 +18,7 @@
 	@echo CC $<
 	@${CC} -c ${CFLAGS} $<
 
-${OBJ}: config.h config.mk
+${OBJ}: config.h config.mk mpdcontrol.c
 
 config.h:
 	@echo creating $@ from config.def.h
